- type: npcFaction
  id: Wastelander
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider

- type: npcFaction
  id: BrotherhoodMidwest
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - Legion

- type: npcFaction
  id: BrotherhoodMidwestSecureArea
  hostile:
  - Wastelander
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - Legion

- type: npcFaction
  id: BrotherhoodWashington
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - Legion

- type: npcFaction
  id: BrotherhoodWashingtonSecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - Legion

- type: npcFaction
  id: CaravanCompany
  hostile:
  - WastelandInsect
  - WastelandAnimal
  - Raider

- type: npcFaction
  id: CaravanCompanySecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - Legion

- type: npcFaction
  id: NCR
  hostile:
  - Zetan
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - Legion

- type: npcFaction
  id: NCRSecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - Legion

- type: npcFaction
  id: Rangers
  friendly:
  - NCR
  hostile:
  - Zetan
  - WastelandInsect
  - WastelandAnimal
  - Raider
  - Legion

- type: npcFaction
  id: Townsfolk
  hostile:
  - Raider

- type: npcFaction
  id: Tribal
  hostile:
  - Raider

- type: npcFaction
  id: Vault
  hostile:
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - Legion

- type: npcFaction
  id: VaultSecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - Legion

- type: npcFaction
  id: Zetan
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - Legion

- type: npcFaction
  id: Raider
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandInsect
  - WastelandAnimal
  - Zetan
  - Legion

- type: npcFaction
  id: WastelandAnimal
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandInsect
  - Raider
  - Legion

- type: npcFaction
  id: WastelandInsect
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - BrotherhoodMidwestSecureArea # turrets
  - BrotherhoodWashingtonSecureArea # turrets
  - CaravanCompany
  - NCR
  - Rangers
  - Townsfolk
  - Tribal
  - Vault
  - WastelandAnimal
  - Raider
  - Legion

- type: npcFaction
  id: LegionSecureArea
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - NCR

- type: npcFaction
  id: Legion
  hostile:
  - Wastelander
  - BrotherhoodMidwest
  - BrotherhoodWashington
  - CaravanCompany
  - Townsfolk
  - Tribal
  - Vault
  - Zetan
  - WastelandAnimal
  - WastelandInsect
  - Raider
  - NCR