- type: job
  id: LegCenturion
  setPreference: true
  name: job-name-leg-centurion
  description: job-description-leg-centurion
  playTimeTracker: JobLegCenturion
  requirements:
    - !type:DepartmentTimeRequirement
      department: Legion
      time: 72000 # 20 hours
  weight: 5
  startingGear: LegCenturionGear
  icon: JobIconDetective
  supervisors: job-supervisors-leg-Centurion
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Legion

- type: startingGear
  id: LegCenturionGear
  equipment:
    jumpsuit: N14ClothingUniformLegion
    shoes: N14ClothingBootsCenturion
    outerClothing: N14ClothingOuterCenturionArmor
    head: N14ClothingHeadHelmetCenturion
    id: N14IDLegionSignaculumLegionary
    hands: N14ClothingHandsGlovesLegion
    back: N14ClothingBackpackMilitary
    pocket1: Legiontrooperloadoutkits
    belt: ClothingBeltRevolverdesertfilled
    mask: N14ClothingMaskCenturion
  innerClothingSkirt: N14ClothingUniformLegion #placeholder
  satchel: N14ClothingBackpackSatchelMilitary
  duffelbag: N14ClothingBackpackDuffelMilitary
